### PR TITLE
Particle filter

### PR DESCRIPTION
**Pull request by Jinxit**
NOTE: Still needs parameters and tweaking, and most likely more ways to retrieve the most likely state
- data/small_maze.txt is the maze in the lab
- map contains lines which contain points, in 2D
- aggregators receive sensor data and merge them appropriately
- observer groups aggregators
- forrest_filter has all the odometry and probability stuff
- particle_filter is the main node, it runs the particle filter and sends points and lines to rviz

### CODE REVIEW

**Comment by GustavSandstroem** [comment]
Kollat lite. Kollar noggrannare efter nästa commit. OK

**Comment by goncacp** [comment]
OK

**Comment by TobiasLundin** [comment]
OK!

**Comment by Thrasi** [comment]
ok

**Pull request merged**
